spy = true
limit_operations = 7
money = 30.0
gain = 30.0
show_details_monitor = true
cryptos = [
  "ETHUSDT", "AVAXUSDT", "ADAUSDT", "LINKUSDT", "DOTUSDT",
  "ATOMUSDT", "GRTUSDT", "SANDUSDT", "MANAUSDT", "ALGOUSDT",
  "INJUSDT", "NEARUSDT", "SUIUSDT", "UNIUSDT", "PIUSDT",
  "XRPUSDT", "BNBUSDT", "DOGEUSDT", "TRXUSDT",
  "BCHUSDT", "TONUSDT", "LTCUSDT", "XMRUSDT",
  "AAVEUSDT", "TAOUSDT", "APTUSDT", "CROUSDT",
  "OKBUSDT", "ICPUSDT", "ETCUSDT", "KASUSDT",
  "ARBUSDT", "FILUSDT", "JUPUSDT", "LDOUSDT",
  "VIRTUALUSDT", "QNTUSDT", "OPUSDT", "TIAUSDT",
  "STXUSDT", "SUSDT", "IPUSDT", "SEIUSDT", "PAXGUSDT",
  "FLRUSDT", "IMXUSDT", "WIFUSDT", "SPXUSDT",
  "DEXEUSDT", "CRVUSDT", "ZECUSDT", "CAKEUSDT",
  "ENSUSDT", "RAYUSDT", "GALAUSDT", "THETAUSDT",
  "JASMYUSDT", "XAUTUSDT", "COREUSDT", "NEXOUSDT",
  "IOTAUSDT", "PENDLEUSDT", "SOLUSDT", "ENAUSDT",
  "BTTUSDT", "HNTUSDT", "XDCUSDT", 
  "XLMUSDT", "HBARUSDT", "VETUSDT", "EOSUSDT", "XTZUSDT", "ONDOUSDT",
  "MKRUSDT", "FETUSDT", "ARUSDT", "AEROUSDT", "KMNOUSDT", "SYRUPUSDT",

"PENGUUSDT", "JTOUSDT", "XTZUSDT", "ZKJUSDT", "FLOWUSDT", "RUNEUSDT", "HNTUSDT", "MANAUSDT", 
"APEUSDT", "ABUSDT", "XCNUSDT", "KAVAUSDT", "DEEPUSDT", "EIGENUSDT", "STRKUSDT", "ATHUSDT", 
"AEROUSDT", "EGLDUSDT", "DYDXUSDT", "XECUSDT", "NEOUSDT", "ARUSDT", "COMPUSDT", "LPTUSDT", "AIOZUSDT", 
"ZBCNUSDT", "KAITOUSDT", "RSRUSDT", "AXSUSDT", "MORPHOUSDT", "CFXUSDT", "SUPERUSDT", "RONUSDT", "CHZUSDT", 
"ETHFIUSDT", "SUNUSDT", "MOVEUSDT", "WUSDT", "GNOUSDT", "FTTUSDT", "AMPUSDT", "TWTUSDT", "JSTUSDT", "AKTUSDT", 
"LUNCUSDT", "BEAMUSDT", "AXLUSDT", "OMUSDT", "CTCUSDT", "SAFEUSDT", "1INCHUSDT", "MASKUSDT", 
"MEWUSDT", "KSMUSDT", "DASHUSDT", "CVXUSDT", "MINAUSDT", "PNUTUSDT", "MXUSDT", "DCRUSDT", "ZROUSDT", "SFPUSDT", 
"TFUELUSDT", "GLMUSDT", "NXPCUSDT", "AI16ZUSDT", "SNXUSDT", "NOTUSDT", "ZILUSDT", "MOCAUSDT", "ASTRUSDT", 
"QTUMUSDT", "TOSHIUSDT", "BLURUSDT", "ZKUSDT", "ROSEUSDT", "GIGAUSDT", "VANAUSDT", 
"IOTXUSDT", "ZRXUSDT", "TRACUSDT", "BATUSDT", "COWUSDT", "GASUSDT", "MOODENGUSDT"
]

[binance]
base_url = "https://api.binance.com/api/v3"
future_url = "https://fapi.binance.com/fapi/v1"
future_url_v2 = "https://fapi.binance.com/fapi/v2"
interval = "1h"
limit = 271
leverage = 1
decide = false
